log-alarm:
  enableTraceId: true
  timeout:
    settings:
      - urlPattern: "^/api.*$" # 匹配以 /test 开头的所有路径
        threshold: 1000000 # 超时时间（毫秒）
  mode: workWechat
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=9df804d2-1dcf-4b34-a1d5-a268d0c053ff
#  mode: dingding
#  webhook: https://oapi.dingtalk.com/robot/send?access_token=7313b1e9717a4c47056d258e8778a3238b9ddc296c333b529c5ae6cca122c045
  exclude:
    #多个逗号隔开
    throwable:
    keyword:
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: your-group-id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "com.ljw.logalarm.dto"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            trusted:
spring:
  application:
    name: test
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#              packages: "com.ljw.logalarm.dto"